import { pgTable, serial, text, timestamp, varchar, boolean } from "drizzle-orm/pg-core";

export const visitors = pgTable("visitors", {
  id: serial("id").primaryKey(),
  visitorId: varchar("visitor_id", { length: 36 }),
  ip: varchar("ip", { length: 45 }).notNull(),
  city: text("city"),
  region: text("region"),
  country: text("country"),
  loc: text("loc"),
  org: text("org"),
  userAgent: text("user_agent"),
  browser: text("browser"),
  os: text("os"),
  device: text("device"),
  referrer: text("referrer"),
  path: text("path"),
  asName: text("as_name"),
  isHosting: boolean("is_hosting").default(false),
  isProxy: boolean("is_proxy").default(false),
  isMobile: boolean("is_mobile").default(false),
  botReason: text("bot_reason"),
  isBot: boolean("is_bot").default(false),
  visitedAt: timestamp("visited_at").defaultNow().notNull(),
});
