import { FaReact, FaNodeJs, FaDocker, FaLink, FaAws } from "react-icons/fa";
import {
  SiNextdotjs,
  SiTailwindcss,
  SiPostgresql,
  SiPrisma,
  SiRedux,
  SiFirebase,
  SiHono,
  SiClerk,
  SiGooglegemini,
  SiMui,
  SiVercel,
  SiDrizzle,
  SiRazorpay,
  SiLangchain,
  SiSpringboot,
  SiCloudflare,
} from "react-icons/si";
import { RiRobot2Line } from "react-icons/ri";
import { TbVector } from "react-icons/tb";

export const techIcons: Record<string, React.ReactNode> = {
  Docker: <FaDocker size={14} />,
  "React.js": <FaReact size={14} />,
  React: <FaReact size={14} />,
  "Node.js": <FaNodeJs size={14} />,
  "Next.js": <SiNextdotjs size={14} />,
  "Spring Boot": <SiSpringboot size={14} />,
  Vercel: <SiVercel size={14} />,
  "Cloudflare Workers": <SiCloudflare size={14} />,
  "Tailwind CSS": <SiTailwindcss size={14} />,
  PostgreSQL: <SiPostgresql size={14} />,
  "Prisma ORM": <SiPrisma size={14} />,
  Redux: <SiRedux size={14} />,
  Firebase: <SiFirebase size={14} />,
  "Gemini API": <SiGooglegemini size={14} />,
  "Material UI": <SiMui size={14} />,
  Hono: <SiHono size={14} />,
  Inngest: <FaLink size={14} />,
  Clerk: <SiClerk size={14} />,
  "TMDB API": <FaLink size={14} />,
  "Drizzle ORM": <SiDrizzle size={14} />,
  Razorpay: <SiRazorpay size={14} />,
  "Vercel AI SDK": <FaLink size={14} />,
  LangChain: <SiLangchain size={14} />,
  "Hugging Face": <RiRobot2Line size={14} />,
  Pinecone: <TbVector size={14} />,
  "AWS S3": <FaAws size={14} />,
};

export const projects = [
  {
    id: "1",
    image: "/pdf-chat.png",
    title: "PDF-Chat",
    category: "Full Stack",
    githubLink: "https://github.com/ArinjayBhola/Chat-PDF",
    liveUrl: "https://chat-pdf-beryl.vercel.app/",
    slug: "pdf-chat",
    description:
      "An AI-driven document chat platform that lets users upload PDFs and images and query their content intelligently. It uses Tesseract OCR for image-based text extraction, converts documents into vector embeddings with Gemini AI(text-embedding-004), stores them in a vector database(Pinecone) for semantic search, and delivers accurate, context-aware responses through a modern Next.js interface.",
    techStack: [
      "Next.js",
      "Tailwind CSS",
      "Vercel AI SDK",
      "Gemini API",
      "LangChain",
      "Hugging Face",
      "Pinecone",
      "AWS S3",
    ],
  },
  {
    id: "2",
    image: "/lms.png",
    title: "LMS",
    category: "Full Stack",
    githubLink: "https://github.com/ArinjayBhola/LMS",
    liveUrl: "https://lms-opal-gamma.vercel.app/dashboard",
    slug: "lms",
    description:
      "An AI-powered learning platform that enables users to design and manage courses easily. It auto-generates notes, quizzes, and flashcards via Gemini AI, with progress tracking and a smooth learning experience.",
    techStack: [
      "Next.js",
      "Tailwind CSS",
      "Inngest",
      "PostgreSQL",
      "Drizzle ORM",
      "Redux",
      "Gemini API",
      "Clerk",
      "Razorpay",
    ],
  },
  {
    id: "3",
    image: "/taskmanagment.png",
    title: "Task Management",
    category: "Full Stack",
    githubLink: "https://github.com/ArinjayBhola/Task-Managment",
    liveUrl: "https://task-managment-8ihr.vercel.app/",
    slug: "task-management",
    description:
      "A productivity tool for managing users and tasks efficiently. Admins can create users, assign tasks, and track activity, while users manage their own workflows with full CRUD capabilities.",
    techStack: ["React.js", "Tailwind CSS", "Material UI", "PostgreSQL", "Prisma ORM", "Hono", "Redux"],
  },
  {
    id: "4",
    image: "/aaolikhen.png",
    title: "Aao Likhen",
    category: "Full Stack",
    githubLink: "https://github.com/ArinjayBhola/Aao-Likhen",
    liveUrl: "https://aao-likhen.vercel.app/signin",
    slug: "aao-likhen",
    description:
      "A blogging platform where authenticated users can write, share, and read blogs, fostering a collaborative writing community.",
    techStack: ["React.js", "Tailwind CSS", "Hono", "PostgreSQL", "Prisma ORM"],
  },
  {
    id: "5",
    image: "/netflix.png",
    title: "Netflix Clone",
    category: "Frontend",
    githubLink: "https://github.com/ArinjayBhola/Netflix-Clone",
    liveUrl: "https://netflix-clone-dun-eta.vercel.app/browse",
    slug: "netflix-clone",
    description:
      "A Netflix-inspired app with Firebase authentication, watchlist management, and AI-powered movie recommendations using Gemini API and TMDB.",
    techStack: ["React.js", "Tailwind CSS", "Firebase", "Gemini API", "TMDB API"],
  },
  {
    id: "6",
    image: "/youtube.png",
    title: "YouTube Clone",
    category: "Frontend",
    githubLink: "https://github.com/ArinjayBhola/Youtube",
    liveUrl: "https://youtube-delta-two.vercel.app/",
    slug: "youtube-clone",
    description:
      "A YouTube clone allowing users to search and watch videos with infinite scrolling for a seamless experience.",
    techStack: ["React.js", "Tailwind CSS", "Redux"],
  },
];

export const experiences = [
  {
    role: "Full Stack Developer Intern",
    company: "Mittal Gupta and Co.",
    duration: "Aug 2025 - Oct 2025",
    description: [
      "Integrated frontend applications with backend services to handle authentication, permissions, and secure data access across multiple user roles.",
      "Collaborated to break down real business problems into technical tasks and deliver features incrementally under guidance.",
      "Optimized secure data access across multiple user roles, ensuring data integrity and compliance.",
    ],
    technologies: ["React", "Node.js"],
  },
  {
    role: "Full Stack Developer Intern",
    company: "Ginete Technologies Pvt. Ltd.",
    duration: "May 2025 - Aug 2025",
    description: [
      "Architected and delivered domain-specific full-stack applications, including internal HR tools and business workflow platforms.",
      "Designed and implemented RESTful APIs, database schemas, and document-handling pipelines using React, Next.js, Node.js, and PostgreSQL.",
      "Owned end-to-end development and deployment, translating business processes into scalable, production-ready systems.",
    ],
    technologies: ["Next.js", "React", "Node.js", "PostgreSQL"],
  },
  {
    role: "Software Engineering Intern",
    company: "Codehop Interfusion Pvt. Ltd",
    duration: "June 2024 – September 2024",
    description: [
      "Led debugging efforts and optimized page functionality to enhance overall user experience, resulting in improved performance and faster load times.",
      "Developed and implemented responsive web pages, driving a smoother and more efficient interaction for end-users.",
      "Collaborated cross-functionally with team members to identify performance bottlenecks, resolve technical issues, and deliver a seamless application experience.",
      "Containerized and deployed APIs using Docker, ensuring a consistent and isolated environment for development, testing, and production.",
    ],
    technologies: ["React.js", "Node.js", "Docker", "Tailwind CSS", "Spring Boot"],
  },
];
